import type { PointsValue } from '../../models/boardSpec';
import type { Draft } from '../../store/toBoardSpec';
import type { OccasionPack } from './types';

export const JESSE_2017_PLAYERS = [
  'Beej', 'Billy', 'Brett', 'Chris B.', 'Chris W.', 'Dan', 'Dave', 'Drew', 'Grant', 'Hugh',
  'Hunter B.', 'Hunter M.', 'James', 'Jesse', 'Jim', 'Jon', 'Kent', 'Luckey', 'Luke', 'Marshall',
  'Mason', 'Matt P.', 'Matt W.', 'Micah', 'Mike', 'Preston', 'Rob L.', 'Rob W.', 'Ryan', 'Steven',
] as const;

type OccasionActivity = { name: string; points: PointsValue; maxPoints?: number };

export const JESSE_2017_ACTIVITIES: OccasionActivity[] = [
  { name: "Eat the Mystery Thing (It's Edible, Mostly)", points: 1 },
  { name: "Don't Sleep in a Bed", points: 2 },
  { name: 'Karaoke Serenade', points: 1, maxPoints: 2 },
  { name: 'Meal Cleanup', points: 1 },
  { name: 'Sleep After 3am', points: 2, maxPoints: 4 },
  { name: 'Sleep Before 7pm', points: -1 },
  { name: '100 Total Pullups', points: 2 },
  { name: '100 Pushups in 10 Minutes', points: 2 },
  { name: '69 Burpees', points: 2 },
  { name: 'Canoe Time Trials', points: { min: 1, max: 5 } },
  { name: 'Catch a Fish (Biggest)', points: 3, maxPoints: 4 },
  { name: 'Indoor Bball Shot', points: 2 },
  { name: 'Win Paintball Duel', points: 2, maxPoints: 4 },
  { name: 'Lose Paintball Duel', points: 1, maxPoints: 4 },
  { name: 'Throwing Axe Bullseye', points: 2 },
  { name: 'Win a Game of CanJam', points: 1 },
  { name: 'Win a Game of Stump', points: 1 },
  { name: 'Win Game of Chess', points: 1 },
  { name: 'Win Hide and Seek', points: 2, maxPoints: 4 },
  { name: '2 Shots in a Row', points: 2, maxPoints: 4 },
  { name: 'Beer Bong', points: 2, maxPoints: 4 },
  { name: 'Buffalo Someone', points: 1, maxPoints: 4 },
  { name: 'Spin Coin, Finish Beer First', points: 2, maxPoints: 4 },
  { name: 'Hit Target with Football', points: 1 },
  { name: 'Life Someone', points: 1, maxPoints: 4 },
  { name: 'Shotgun a Beer', points: 1, maxPoints: 3 },
  { name: 'Bleed (Involuntarily)', points: 1 },
  { name: 'Eat a (Really Hot) Pepper', points: 2 },
  { name: 'Jump in the Lake', points: 2, maxPoints: 4 },
  { name: 'Throw Up', points: 2, maxPoints: 8 },
  { name: 'Drink 2 Beers in Handcuffs', points: 2 },
  { name: 'Beer Pong Tournament', points: { min: 0, max: 4 } },
  { name: 'Ping Pong Tournament', points: { min: 0, max: 4 } },
  { name: 'Pool Tournament', points: { min: 0, max: 4 } },
  { name: 'RPS Tournament', points: { min: 0, max: 4 } },
  { name: 'Know the Name', points: 2 },
  { name: 'Bonus Awarded by Bachelor', points: { min: 1, max: 5 } },
];

export const JESSE_2017_RULES: Draft['rules'] = [
  {
    heading: 'JESSE CORDELL MADDOX, III’S BACHELOR PARTY GAME RULES, INDEMNIFICATION, AND NON-DISCLOSURE AGREEMENT',
    text: "YOUR PARTICIPATION AT THE BACHELOR PARTY IS SUBJECT TO THE TERMS HEREIN. THE FOLLOWING IS THE AGREEMENT THAT MUST BE AGREED TO THAT WILL EXIST BETWEEN YOU AND JESSE CORDELL MADDOX, III AND ALL OTHER PARTICIPANTS.",
  },
  {
    heading: 'SECTION 1. GAME RULES',
    text: `BUFFALO
PARTICIPANTS MUST DRINK ANY BEVERAGE CONTAINING ALCOHOL WITH THEIR LEFT HAND ONLY.

IF A BUFFALO CLUB MEMBER VIOLATES THE LEFT HAND RULE, ANOTHER BUFFALO CLUB MEMBER MAY CALL OUT “BUFFALO!” AND THE VIOLATOR MUST FINISH THE REMAINDER OF THE BEVERAGE QUICKLY USING THEIR LEFT HAND OF COURSE. REALISTIC EXPECTATIONS SHALL BE OBSERVED DURING AN EXCESSIVE VIOLATION AND THE PUNISHMENT WILL BE DECIDED UPON BY THE SURROUNDING MEMBERS.

LIFE
PARTICIPANTS SHOULD PUT A DENT ON ANY CANNED ALCOHOLIC BEVERAGE THEY ARE DRINKING FROM. SHOULD SOME CALL “LIFE!” AT ANOTHER PERSON, IF THAT PERSON DOES NOT HAVE A DENT IN THEIR CAN THEY MUST FINISH THE REMAINDER OF THEIR BEVERAGE QUICKLY AND IMMEDIATELY. SHOULD THE PERSON HAVE A DENT IN THEIR CAN, THE PERSON WHO YELLED “LIFE!” MUST FINISH THEIR OWN BEVERAGE OR PROCURE ONE TO CHUG.

BEER PONG
TEAMS OF TWO PARTICIPATE. ONE RACK OF 10 CUPS. EACH TEAM GETS ONE RE-RACK. DEFENSE PERMITTED ONLY ON BOUNCES, WHICH COUNT FOR TWO CUPS. A COURTESY RE-RACK WILL BE GIVEN TO THE OTHER TEAM SHOULD ONE TEAM FINISH ALL OF THEIR CUPS. SUCCESSFUL REBUTTALS LEAD TO A SIX-CUP TIEBREAKER.

POOL
STANDARD POOL RULES. ALL SCRATCHES ARE BALL-IN-HAND. SCRATCHES RESULT FROM POCKETING THE CUE BALL, HITTING YOUR OPPONENT’S BALL BEFORE YOUR OWN, OR NOT HITTING YOUR OWN BALL DURING A TURN.

CANOE TIME TRIALS
TEAMS OF THREE SHALL PARTICIPATE. THE TEAM WILL ENTER THE CANOE ALONG WITH FIVE BEERS. STARTING AT THE FIRST BUOY, THE TIME SHALL START AND THE CANOE MUST TRAVEL AROUND THE FAR BUOY AND RETURN. TIME IS FINISHED AFTER BOTH THE CANOE HAS PASSED THE FIRST BUOY AND ALL BEERS HAVE BEEN FINISHED.

KARAOKE SERENADE
A PARTICIPANT MAY EARN A KARAOKE POINT BY SELECTING A SONG AND SINGING IT OVER THE HOUSE SOUND SYSTEM TO OTHER MEMBERS. SHOULD THEIR BE GENERAL AGREEMENT THAT IT WAS A POOR OR HALF-HEARTED PERFORMANCE, NO POINTS SHALL BE AWARDED.

CATCH A FISH
FISH MUST BE LONGER THAN 5 INCHES LONG FOR A POINT TO BE AWARDED.

PAINTBALL DUEL
EACH PARTICIPANT MUST WEAR SAFETY EQUIPMENT. AN OBSERVER MUST BE PRESENT. STANDING BACK TO BACK, THE OBSERVER WILL COUNT TO 15 AS EACH PARTICIPANT TAKES 15 STEPS. IMMEDIATELY AFTER “15” IS YELLED, THE PARTICIPANTS MAY TURN AROUND AND FIRE AT THEIR OPPONENT. THE FIRST PERSON TO SHOOT THE OTHER PLAYER WILL BE DEEMED THE WINNER. HEADSHOTS ARE NOT ALLOWED AND DO NOT COUNT. THE RULING OF THE OBSERVER IS FINAL.

HIDE AND SEEK
THE BACHELOR AT ANY POINT MAY DECIDE TO HIDE. AN OBSERVER WILL ANNOUNCE “HIDE AND SEEK”. THE FIRST PARTICIPANT TO FIND THE BACHELOR SHALL BE AWARDED A POINT. 5 MINUTE TIME LIMIT. IF NOBODY FINDS THE BACHELOR, HE RECEIVES THE POINTS.

KNOW THE NAME
AT ANY POINT, ASK THE BACHELOR TO PLAY “KNOW THE NAME”. THE BACHELOR WILL THEN POINT TO SOMEONE. TELL THE BACHELOR THE PERSON’S NAME FOR A POINT.

COIN RACE
A PARTICIPANT WILL HAVE A NEWLY OPENED 12 OUNCE BEVERAGE. THEY WILL THEN SPIN A COIN ON THE TABLE. IF THEY FINISH THEIR BEVERAGE BEFORE THE COIN FALLS STILL, THE PARTICIPANT WILL EARN A POINT.

ROCK PAPER SCISSORS!
BEST TWO OUT OF THREE. MAY THE LUCKIEST MOTHERFUCKER WIN.`,
  },
  {
    heading: 'SECTION 2. GENERAL CONDUCT',
    text: `IN THE CONTRACT/OATH BELOW, YOU MUST ADHERE TO ALL GUIDELINES AND PROCEDURES IN A STRICT FASHION.

I WILL ACT LIKE I AM FIVE AND PROMOTE IMMATURE BEHAVIOR THE WHOLE WEEKEND, INCLUDING LOUD, OBNOXIOUS OUTBURSTS. I WILL CONSUME ALCOHOLIC BEVERAGES AND PROMOTE DRUNKENLY MISCONDUCT IN THE MOST APPROPRIATE FASHION. I WILL PROMOTE ANIMALISTIC BEHAVIOR AND SHALL ADOPT “DEBAUCHERY” AS MY MIDDLE NAME FOR THE DURATION OF THE EVENT.

ANOTHER MEMBER OF THE PARTY WHO HAS TOO MUCH ALCOHOL OR HAS POOR TASTE AND IS SPEAKING IN AN OBNOXIOUS MANNER FOR MORE THAN ONE MINUTE MUST BE ESCORTED BACK TO A SAFE PLACE TO COOL OFF.

I MUST EMBARRASS MYSELF AT LEAST ONCE PER HOUR.

IN CASE OF THE EMERGENCY OF ANOTHER MEMBER OF THE PARTY NEEDING TO PRAY TO THE PORCELAIN GODDESS OR VISIT MR. TIDY BOWL MAN, IT IS ESSENTIAL THAT I MAKE SURE ONE BACHELOR BRETHREN GOES WITH THE OTHER BRETHREN IN NEED (BIN).

I WILL NOT, AT ANY TIME, THINK OF WORK-RELATED MATTERS. IF WORK DOES CONSUME MY MIND, I WILL FORFEIT PARTY STATUS AND BE SEEN AS AN OUTCAST BY THE OTHER PARTIES.`,
  },
  {
    heading: 'SECTION 3. CONFIDENTIAL INFORMATION',
    text: `CONFIDENTIAL INFORMATION MEANS ANY INFORMATION DISCLOSED TO BY ONE PARTY TO THE OTHER, EITHER DIRECTLY OR INDIRECTLY IN WRITING, ORALLY OR BY INSPECTION OF TANGIBLE OR INTANGIBLE OBJECTS, INCLUDING WITHOUT LIMITATION DOCUMENTS, TRAVEL PLANS, EMAILS, PHONE CONVERSATIONS, RESERVATIONS, FINANCIAL RECORDS, DRUNKEN STUPOR, WRITTEN LETTERS AND ALL OTHER FORMS OF TRADITIONAL AND DIGITAL MEDIA. CONFIDENTIAL INFORMATION MAY ALSO INCLUDE INFORMATION DISCLOSED TO A PARTY BY THIRD PARTIES AT THE DIRECTION OF A DISCLOSING PARTY. THE BACHELOR PARTY PLANNERS DISCLOSING THE CONFIDENTIAL INFORMATION SHALL BE REFERRED TO AS “DISCLOSING PARTY” IN THE AGREEMENT AND YOU, THE PARTY RECEIVING THE CONFIDENTIAL INFORMATION SHALL BE REFERRED TO AS “RECEIVING PARTY” IN THE AGREEMENT. ALL MEMBERS OFFICIALLY INVITED TO THE BACHELOR PARTY WILL BE REFERRED TO AS “THE TEAM”.`,
  },
  {
    heading: 'SECTION 4. NON-USE AND NON-DISCLOSURE',
    text: `THE RECEIVING PARTY AGREES NOT TO USE ANY CONFIDENTIAL INFORMATION FOR ANY PURPOSE EXCEPT TO EVALUATE AND ENGAGE PLANNING AND PARTICIPATION IN THE BACHELOR PARTY. RECEIVING PARTY AGREES NOT TO DISCLOSE ANY CONFIDENTIAL INFORMATION TO THIRD PARTIES, FRIENDS, WIVES, BOYFRIENDS, GIRLFRIENDS, SIGNIFICANT OTHERS OR ANYONE OUTSIDE THE TEAM. KNOWINGLY OR UNKNOWINGLY THE RECEIVING PARTY WILL MAINTAIN THIS NON-USE AND NON-DISCLOSURE AGREEMENT FOR THE ENTIRE LIFESPAN OF ALL MEMBERS OF THE TEAM. P.S. WHISPER “OCTOPUS” IN THE BACHELOR’S EAR FOR ONE BONUS POINT.`,
  },
  {
    heading: 'SECTION 5. MAINTENANCE OF CONFIDENTIALITY INFORMATION',
    text: `THE RECEIVING PARTY AGREES THAT IT SHALL TAKE ANY AND ALL MEASURES TO PROTECT THE SECRECY OF AND AVOID DISCLOSURE AND UNAUTHORIZED USE OF THE CONFIDENTIAL INFORMATION. WITHOUT LIMITING THE FOREGOING, RECEIVING PARTY SHALL TAKE AT LEAST THOSE MEASURES THAT RECEIVING PARTY TAKES TO PROTECT ITS OWN MOST HIGHLY CONFIDENTIAL INFORMATION. THE RECEIVING PARTY SHALL NOT MAKE ANY COPIES OF CONFIDENTIAL INFORMATION. THE RECEIVING PARTY SHALL NOT REPRODUCE THE DISCLOSING PARTY’S CONFIDENTIAL INFORMATION BEFORE, DURING OR AFTER THE BACHELOR PARTY. THIS INCLUDES EMAIL, SOCIAL MEDIA STATUS UPDATES, PHOTO UPDATES. ANY MEDIA THAT IS CAPTURED BY THE TEAM MUST BE APPROVED BY ALL MEMBERS OF THE BACHELOR PARTY PLANNERS OTHERWISE IT WILL BE DELETED UPON COMPLETION OF THE BACHELOR PARTY.`,
  },
  {
    heading: 'SECTION 6. TERM',
    text: 'THIS AGREEMENT SHALL SURVIVE FOR THE TOTAL COMBINED LIFESPAN OF ALL MEMBERS OF THE TEAM.',
  },
];

export function createJesse2017Draft(): Draft {
  return {
    title: 'THE BACHELOR WEEKEND OF',
    honoree: 'JESSE CORDELL MADDOX, III',
    subtitle: 'OCTOBER 19–22, 2017',
    players: [...JESSE_2017_PLAYERS],
    activities: JESSE_2017_ACTIVITIES.map((activity) => ({
      uid: crypto.randomUUID(),
      ...structuredClone(activity),
      bonus: false,
    })),
    libraryOccasion: 'bachelor',
    posterSize: '60x48',
    template: 'landscapeBrackets',
    letterHeaderStyle: 'large',
    includeRules: true,
    brackets: [
      { title: 'BEER PONG', slots: 8, teamSize: 2 },
      { title: 'PING PONG', slots: 16, teamSize: 1 },
      { title: 'POOL', slots: 16, teamSize: 1 },
      { title: 'ROCK PAPER SCISSORS!', slots: 16, teamSize: 1 },
    ],
    pointsRangeFormat: 'dash',
    totalsTarget: 100,
    rulesTitle: '',
    rulesContent: JESSE_2017_RULES
      .map((rule) => `**${rule.heading}**\n${rule.text}`)
      .join('\n\n'),
    rulesHeadingSuffix: 'none',
    rules: [],
    footnote: '',
    writeInRows: 0,
    honoreeBonusRow: false,
    cornerBoxes: [
      'GRAND CHAMPION',
      '2ND PLACE (VALIANT EFFORT)',
      '3RD PLACE (WORTHY COMPETITOR)',
      'GRAND LOSER (R.I.P.)',
    ],
    theme: {
      rowTint: '#F4F8FB',
      highlightPointsHeader: true,
      bonusBracket: false,
      headerDivider: true,
      titleColor: '#4FC3CB',
      accentColor: '#3A6BC7',
      activityColor: '#3A6BC7',
      highlightColor: '#141414',
      pointsColTint: '',
      maxPointsColTint: '',
      cornerLabel: 'THE GAME',
      cornerSubLabel: 'ACTIVITIES',
      allCaps: true,
    },
  };
}

export const JESSE_2017_OCCASION: OccasionPack = {
  id: 'jesse-bachelor-2017',
  name: 'Jesse Maddox Bachelor 2017',
  description: 'The complete 2017 roster, scoring activities, results boxes, target, and agreement.',
  createDraft: createJesse2017Draft,
};
