import type { Theme } from '@/models/theme';
import { CategoryColors } from '@/models/board';

const defaultCategoryColors = { ...CategoryColors };

const SYSTEM_FONTS = 'Arial, Helvetica, sans-serif';
const SERIF_FONTS = 'Georgia, "Times New Roman", serif';
const MONO_FONTS = '"Courier New", Courier, monospace';

export const THEMES: Theme[] = [
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Clean and modern with sharp lines',
    colors: {
      background: '#FFFFFF',
      headerBackground: '#1a1a1a',
      headerText: '#FFFFFF',
      gridBackground: '#FFFFFF',
      gridLineColor: '#333333',
      gridLineWidth: 2,
      cellBackground: '#FFFFFF',
      cellAlternateBackground: '#F5F5F5',
      cellText: '#333333',
      taskLabelBackground: '#F0F0F0',
      taskLabelText: '#1a1a1a',
      pointsBackground: '#E8E8E8',
      pointsText: '#1a1a1a',
      playerHeaderBackground: '#2a2a2a',
      playerHeaderText: '#FFFFFF',
      scoreboardBackground: '#1a1a1a',
      scoreboardText: '#FFFFFF',
      bracketBackground: '#F8F8F8',
      bracketLineColor: '#333333',
      bracketText: '#1a1a1a',
      rulesBackground: '#F0F0F0',
      rulesText: '#333333',
      accentColor: '#FF6B35',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${SYSTEM_FONTS}`,
      subtitle: SYSTEM_FONTS,
      bachelorName: `bold ${SYSTEM_FONTS}`,
      playerName: `bold ${SYSTEM_FONTS}`,
      taskLabel: SYSTEM_FONTS,
      cellText: SYSTEM_FONTS,
      body: SYSTEM_FONTS,
    },
    decorations: {
      headerStyle: 'underline',
      checkboxStyle: 'square',
      cornerDecoration: false,
      borderStyle: 'solid',
      borderWidth: 3,
    },
    spacingMultiplier: 1.0,
  },
  {
    id: 'sports',
    name: 'Sports',
    description: 'Bold and energetic like a stadium scoreboard',
    colors: {
      background: '#0A1628',
      headerBackground: '#D4AF37',
      headerText: '#0A1628',
      gridBackground: '#0F1D32',
      gridLineColor: '#D4AF37',
      gridLineWidth: 2,
      cellBackground: '#0F1D32',
      cellAlternateBackground: '#162440',
      cellText: '#FFFFFF',
      taskLabelBackground: '#162440',
      taskLabelText: '#D4AF37',
      pointsBackground: '#1a2d50',
      pointsText: '#D4AF37',
      playerHeaderBackground: '#D4AF37',
      playerHeaderText: '#0A1628',
      scoreboardBackground: '#D4AF37',
      scoreboardText: '#0A1628',
      bracketBackground: '#0F1D32',
      bracketLineColor: '#D4AF37',
      bracketText: '#FFFFFF',
      rulesBackground: '#162440',
      rulesText: '#CCCCCC',
      accentColor: '#D4AF37',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${SYSTEM_FONTS}`,
      subtitle: `bold ${SYSTEM_FONTS}`,
      bachelorName: `bold ${SYSTEM_FONTS}`,
      playerName: `bold ${SYSTEM_FONTS}`,
      taskLabel: `bold ${SYSTEM_FONTS}`,
      cellText: SYSTEM_FONTS,
      body: SYSTEM_FONTS,
    },
    decorations: {
      headerStyle: 'banner',
      checkboxStyle: 'square',
      cornerDecoration: true,
      borderStyle: 'double',
      borderWidth: 4,
    },
    spacingMultiplier: 1.1,
  },
  {
    id: 'retro',
    name: 'Retro',
    description: 'Vintage vibes with warm tones',
    colors: {
      background: '#FDF5E6',
      headerBackground: '#8B4513',
      headerText: '#FDF5E6',
      gridBackground: '#FFF8DC',
      gridLineColor: '#8B4513',
      gridLineWidth: 2,
      cellBackground: '#FFF8DC',
      cellAlternateBackground: '#FAEBD7',
      cellText: '#3E2723',
      taskLabelBackground: '#DEB887',
      taskLabelText: '#3E2723',
      pointsBackground: '#D2B48C',
      pointsText: '#3E2723',
      playerHeaderBackground: '#8B4513',
      playerHeaderText: '#FDF5E6',
      scoreboardBackground: '#8B4513',
      scoreboardText: '#FDF5E6',
      bracketBackground: '#FAEBD7',
      bracketLineColor: '#8B4513',
      bracketText: '#3E2723',
      rulesBackground: '#DEB887',
      rulesText: '#3E2723',
      accentColor: '#CD853F',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${SERIF_FONTS}`,
      subtitle: `italic ${SERIF_FONTS}`,
      bachelorName: `bold ${SERIF_FONTS}`,
      playerName: `bold ${SERIF_FONTS}`,
      taskLabel: SERIF_FONTS,
      cellText: SERIF_FONTS,
      body: SERIF_FONTS,
    },
    decorations: {
      headerStyle: 'box',
      checkboxStyle: 'circle',
      cornerDecoration: true,
      borderStyle: 'double',
      borderWidth: 4,
    },
    spacingMultiplier: 1.05,
  },
  {
    id: 'tactical',
    name: 'Tactical',
    description: 'Military-inspired ops board',
    colors: {
      background: '#1B1B1B',
      headerBackground: '#2D5016',
      headerText: '#C8E6C9',
      gridBackground: '#222222',
      gridLineColor: '#4CAF50',
      gridLineWidth: 1,
      cellBackground: '#222222',
      cellAlternateBackground: '#2A2A2A',
      cellText: '#C8E6C9',
      taskLabelBackground: '#2D3A2D',
      taskLabelText: '#81C784',
      pointsBackground: '#1B2E1B',
      pointsText: '#4CAF50',
      playerHeaderBackground: '#2D5016',
      playerHeaderText: '#C8E6C9',
      scoreboardBackground: '#2D5016',
      scoreboardText: '#C8E6C9',
      bracketBackground: '#2A2A2A',
      bracketLineColor: '#4CAF50',
      bracketText: '#C8E6C9',
      rulesBackground: '#2D3A2D',
      rulesText: '#A5D6A7',
      accentColor: '#4CAF50',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${MONO_FONTS}`,
      subtitle: MONO_FONTS,
      bachelorName: `bold ${MONO_FONTS}`,
      playerName: `bold ${MONO_FONTS}`,
      taskLabel: MONO_FONTS,
      cellText: MONO_FONTS,
      body: MONO_FONTS,
    },
    decorations: {
      headerStyle: 'box',
      checkboxStyle: 'square',
      cornerDecoration: false,
      borderStyle: 'solid',
      borderWidth: 2,
    },
    spacingMultiplier: 0.95,
  },
  {
    id: 'western',
    name: 'Western',
    description: 'Rustic cowboy saloon style',
    colors: {
      background: '#F5E6D3',
      headerBackground: '#5D4037',
      headerText: '#FFECB3',
      gridBackground: '#EFDCC4',
      gridLineColor: '#5D4037',
      gridLineWidth: 2,
      cellBackground: '#EFDCC4',
      cellAlternateBackground: '#E6D0B5',
      cellText: '#3E2723',
      taskLabelBackground: '#D7CCC8',
      taskLabelText: '#3E2723',
      pointsBackground: '#BCAAA4',
      pointsText: '#3E2723',
      playerHeaderBackground: '#5D4037',
      playerHeaderText: '#FFECB3',
      scoreboardBackground: '#5D4037',
      scoreboardText: '#FFECB3',
      bracketBackground: '#E6D0B5',
      bracketLineColor: '#5D4037',
      bracketText: '#3E2723',
      rulesBackground: '#D7CCC8',
      rulesText: '#3E2723',
      accentColor: '#FF8F00',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${SERIF_FONTS}`,
      subtitle: `italic ${SERIF_FONTS}`,
      bachelorName: `bold ${SERIF_FONTS}`,
      playerName: `bold ${SERIF_FONTS}`,
      taskLabel: SERIF_FONTS,
      cellText: SERIF_FONTS,
      body: SERIF_FONTS,
    },
    decorations: {
      headerStyle: 'banner',
      checkboxStyle: 'star',
      cornerDecoration: true,
      borderStyle: 'double',
      borderWidth: 4,
    },
    spacingMultiplier: 1.1,
  },
  {
    id: 'casino',
    name: 'Casino',
    description: 'Las Vegas high-roller vibes',
    colors: {
      background: '#1A0A2E',
      headerBackground: '#FFD700',
      headerText: '#1A0A2E',
      gridBackground: '#1E0E35',
      gridLineColor: '#FFD700',
      gridLineWidth: 2,
      cellBackground: '#1E0E35',
      cellAlternateBackground: '#261445',
      cellText: '#FFFFFF',
      taskLabelBackground: '#2D1B4E',
      taskLabelText: '#FFD700',
      pointsBackground: '#351F5E',
      pointsText: '#FFD700',
      playerHeaderBackground: '#FFD700',
      playerHeaderText: '#1A0A2E',
      scoreboardBackground: '#FFD700',
      scoreboardText: '#1A0A2E',
      bracketBackground: '#261445',
      bracketLineColor: '#FFD700',
      bracketText: '#FFFFFF',
      rulesBackground: '#2D1B4E',
      rulesText: '#E0E0E0',
      accentColor: '#FF1744',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${SYSTEM_FONTS}`,
      subtitle: `italic ${SYSTEM_FONTS}`,
      bachelorName: `bold ${SYSTEM_FONTS}`,
      playerName: `bold ${SYSTEM_FONTS}`,
      taskLabel: SYSTEM_FONTS,
      cellText: SYSTEM_FONTS,
      body: SYSTEM_FONTS,
    },
    decorations: {
      headerStyle: 'banner',
      checkboxStyle: 'diamond',
      cornerDecoration: true,
      borderStyle: 'double',
      borderWidth: 4,
    },
    spacingMultiplier: 1.05,
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon-lit futuristic grid',
    colors: {
      background: '#0D0D0D',
      headerBackground: '#0D0D0D',
      headerText: '#00FFFF',
      gridBackground: '#111111',
      gridLineColor: '#00FFFF',
      gridLineWidth: 1,
      cellBackground: '#111111',
      cellAlternateBackground: '#1A1A1A',
      cellText: '#E0E0E0',
      taskLabelBackground: '#1A1A1A',
      taskLabelText: '#FF00FF',
      pointsBackground: '#1A1A1A',
      pointsText: '#00FF00',
      playerHeaderBackground: '#1A1A1A',
      playerHeaderText: '#00FFFF',
      scoreboardBackground: '#0D0D0D',
      scoreboardText: '#00FFFF',
      bracketBackground: '#1A1A1A',
      bracketLineColor: '#FF00FF',
      bracketText: '#E0E0E0',
      rulesBackground: '#1A1A1A',
      rulesText: '#AAAAAA',
      accentColor: '#FF00FF',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${MONO_FONTS}`,
      subtitle: MONO_FONTS,
      bachelorName: `bold ${MONO_FONTS}`,
      playerName: `bold ${MONO_FONTS}`,
      taskLabel: MONO_FONTS,
      cellText: MONO_FONTS,
      body: MONO_FONTS,
    },
    decorations: {
      headerStyle: 'underline',
      checkboxStyle: 'square',
      cornerDecoration: false,
      borderStyle: 'solid',
      borderWidth: 2,
    },
    spacingMultiplier: 0.95,
  },
  {
    id: 'outdoors',
    name: 'Outdoors',
    description: 'Nature-inspired adventure theme',
    colors: {
      background: '#E8F5E9',
      headerBackground: '#2E7D32',
      headerText: '#FFFFFF',
      gridBackground: '#F1F8E9',
      gridLineColor: '#2E7D32',
      gridLineWidth: 2,
      cellBackground: '#F1F8E9',
      cellAlternateBackground: '#DCEDC8',
      cellText: '#1B5E20',
      taskLabelBackground: '#C8E6C9',
      taskLabelText: '#1B5E20',
      pointsBackground: '#A5D6A7',
      pointsText: '#1B5E20',
      playerHeaderBackground: '#2E7D32',
      playerHeaderText: '#FFFFFF',
      scoreboardBackground: '#2E7D32',
      scoreboardText: '#FFFFFF',
      bracketBackground: '#DCEDC8',
      bracketLineColor: '#2E7D32',
      bracketText: '#1B5E20',
      rulesBackground: '#C8E6C9',
      rulesText: '#1B5E20',
      accentColor: '#FF9800',
      categoryColors: defaultCategoryColors,
    },
    fonts: {
      title: `bold ${SYSTEM_FONTS}`,
      subtitle: SYSTEM_FONTS,
      bachelorName: `bold ${SYSTEM_FONTS}`,
      playerName: `bold ${SYSTEM_FONTS}`,
      taskLabel: SYSTEM_FONTS,
      cellText: SYSTEM_FONTS,
      body: SYSTEM_FONTS,
    },
    decorations: {
      headerStyle: 'banner',
      checkboxStyle: 'circle',
      cornerDecoration: true,
      borderStyle: 'solid',
      borderWidth: 3,
    },
    spacingMultiplier: 1.0,
  },
];

export function getTheme(id: string): Theme {
  const theme = THEMES.find((t) => t.id === id);
  if (!theme) return THEMES[0]!;
  return theme;
}
