export const ACTIVITY_ID_ALIASES: Readonly<Record<string, string>> = {
  'fam-taste-test': 'blind-snack-rank',
  'ann-blind-taste': 'blind-snack-rank',
  'fri-blind-taste': 'blind-snack-rank',
  'gen-taste-mystery': 'blind-snack-rank',
  'fam-photo-recreate': 'recreate-photo',
  'ann-photo-recreate': 'recreate-photo',
  'fri-first-coffee': 'first-up-coffee',
  'fam-timeline-build': 'family-timeline',
  'kid-thank-you-note': 'thank-you-note',
  'fam-help-cleanup': 'meal-cleanup',
  'fri-plate-wash': 'meal-cleanup',
  'gen-help-clean': 'cabin-improvement',
  'fri-cabin-fix': 'cabin-improvement',
  'fam-toast-honor': 'specific-toast',
  'gen-toast': 'specific-toast',
  'fri-toast-story': 'specific-toast',
  'kid-set-table': 'set-table',
  'fam-help-setup': 'set-table',
  'bte-card-game-win': 'board-game-win',
  'kid-card-game': 'board-game-win',
  'bch-dance-floor-stranger': 'invite-one-dance',
  'bte-dance-with-stranger': 'invite-one-dance',
  'kid-talent-show': 'talent-share',
  'fri-talent-share': 'talent-share',
  'gen-mini-talent': 'talent-share',
  'fam-interview-elder': 'family-interview',
  'bch-cornhole-champ': 'cornhole-win',
  'bte-cornhole-win': 'cornhole-win',
  'fri-cornhole-champ': 'cornhole-win',
  'gen-cornhole-score': 'cornhole-win',
  'bch-sunrise-photo': 'sunrise-view',
  'fri-sunrise-watch': 'sunrise-view',
  'bch-cold-plunge': 'cold-water-plunge',
  'fri-cold-plunge': 'cold-water-plunge',
  'sea-cold-plunge': 'cold-water-plunge',
  'bch-arm-wrestle': 'safe-arm-wrestle',
  'fri-arm-wrestle': 'safe-arm-wrestle',
  'gen-arm-wrestle': 'safe-arm-wrestle',
  'bch-karaoke-solo': 'karaoke-song',
  'bte-karaoke-verse': 'karaoke-song',
  'fri-karaoke-song': 'karaoke-song',
  'bch-group-photo-pose': 'group-photo-pose',
  'bte-group-selfie': 'group-photo-pose',
  'gen-group-photo': 'group-photo-pose',
};

export function canonicalActivityId(id: string | undefined): string | undefined {
  return id === undefined ? undefined : (ACTIVITY_ID_ALIASES[id] ?? id);
}
